project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from register import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^book/$',views.book,name='book'),
    url(r'^special/',views.special,name='special'),
    url(r'^register/',include('register.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),

]

register/urls.py
from django.conf.urls import url
from register import views
# SET THE NAMESPACE!
app_name = 'register'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    # url(r'^book/$',views.book,name='book'),

]

register/models.py

from django.db import models
from django.contrib.auth.models import User
from django import forms

# from django_select2.forms import Select2MultipleWidget
# from multiselectfield import MultiSelectField
# from django-weekday-field import weekday_field

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # Name = self.user.username
    Name = models.CharField("Name", max_length=100)
    address = models.CharField(max_length=300)
    phone = models.CharField("Phone no.", max_length=20, blank=True)
    age = models.CharField(max_length=3)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
   
def __str__(self):
  return self.user.username
# def 

class doctors(models.Model):
    d_id = models.AutoField(primary_key=True)
    Name = models.CharField("Name", max_length=100)
    address = models.CharField(max_length=300)
    phone = models.CharField("Phone no.", max_length=20, blank=True)
    email_address = models.EmailField("Email Address", blank=True) 
    department=(
      ('GENERALMEDICINE','GENERALMEDICINE'),
      ('PAEDIATRICS','PAEDIATRICS'),
      ('ONCOLOGY','ONCOLOGY'),
      ('CARDIOLOGIST','CARDIOLOGIST'),
      ('DERMATOLOGIST','DERMATOLOGIST'),
    )
  
    specialisation = models.CharField(
      max_length=20,choices=department,
      default='GENERALMEDICINE',
    )

    num_choices = ( ("1", "ONE"), ("2", "TWO"), ("3", "Three"), ("4", "Four"))
    day = models.CharField(max_length = 15, choices = num_choices)
    # addr=forms.MultipleChoiceField(choices=num_choices,widget=Select2MultipleWidget)
    # num_list = forms.MultipleChoiceField(choices=num_choices, required=True, widget=forms.CheckboxSelectMultiple(), label='Select No', initial=("1", "2"))
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    # weekdays = weekday_field.WeekdayField()

# def __str__(self):
#   return self.user.username

register/forms.py
from django import forms
from register.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    # name = forms.CharField(label='First Name', max_length=100)
    # lname = forms.CharField(label='Last Name', max_length=100)

    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
        
class UserProfileInfoForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput())
    # name = forms.CharField(label='First Name', max_length=100)
    class Meta():
        model = UserProfileInfo
        fields = ('Name','address','phone','age','profile_pic')

register/views.py

from django.shortcuts import render
from register.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request,'dapp/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def book(request):
    return render(request,'dapp/Booking.html')



def register(request):
    registered = False
    if request.method == 'POST':
        
        # Name = (data=request.POST)
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'dapp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dapp/login.html', {})

templates/dapp/Booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <body background="static\hospital.png" style="background-size: 100%;align-content: center;"></body> -->

    <style>
        
        body{
            background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),url(hospital.png) ;
            height: 100vh;
            background-size: cover;
            background-position: center;
        }
        .booking-box{
            max-width: 350px;
            border: 1px solid rgb(12, 3, 3) ;
            margin: 10% auto 0;
        }
        .booking-form{
            padding: 0 20px 20px;
        }
        .booking-form label{
            margin-bottom: 5px;
            margin-top: 10px;
            font-size: 12px;
            color: #fff;
        }
    </style>
    <!-- <link rel="stylesheet" href="templates\dapp\style1.css"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class = "booking-box">
       <div class="booking-form">
            <div class="input-group-btn">
                <label>Doctors</label>
                <select class="custom-select">
                    <option value="1">Doctor1</option>
                    <option value="1">Doctor2</option>
                    <option value="1">Doctor3</option>
                </select>
            </div>
            <div class="input-group-btn">
                <label>Specialization</label>
                <select class="custom-select">
                    <option value="1">Specialization1</option>
                    <option value="2">Specialization2</option>
                    <option value="3">Specialization3</option>
                </select>
            </div>
            <div class="input-grp">
                <label>Date</label>
                <input type="date" class="form-control select-date">
            </div>
            <div class="input-grp">
                <label>Time</label>
                <input type="time" class="form-control select-time">
            </div>
            <div class="input-group-btn">
            <button type="button"class="btn btn-primary" >Book </button>

            </div>
         </div>
    </div>
      
</body>
</html>

templates/dapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <body background="static\hospital.png" style="background-size: 100%;align-content: center;"></body>
      <style>
        .header {
        padding: 10px;
        text-align: center;
        background:lightblue;
        color: lightcoral;
      }
      </style>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'register:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'register:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/dapp/index.html
{% extends "dapp/base.html" %}
{% block body_block %}
<body background="static\hospital.png" style="background-size: 100%;align-content: center;"></body>

<div class="container">
  <div class="jumbotron">
    <h2>HOSPITAL BOOKING SYSTEM</h2>
    {% if user.is_authenticated %}
        <h3>Hello {{ user.username }}</h3>
        <br></br>
        <a class="navbar-link-book" href="{% url 'book' %}">Book Appoinment</a> 
        <style>
          .navbar-link-book{
          padding: 10px;
          text-align: center;
          background:lightblue;
          color: black;
          font-size: 16px;
          
        }
        </style>
    {% else %}
        <h2>Login to make bookings</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/dapp/login.html
{% extends 'dapp/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'register:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/dapp/registration.html
{% extends "dapp/base.html" %}
{% load static %}
{% block body_block %}
<body background="static\hospital.png" style="background-size: 100%;align-content: center;"></body>

  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h2>Register Here</h2>
        
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}